version: '3.3'

services:
    db:
        image: bitnami/postgresql:11
        ports:  
            - 5439:5432  
        volumes:  
            - postgresql_cam_web_sale:/bitnami/postgresql  
        env_file:  
            - .docker.env  
        restart: always  
        networks:  
            - web-cam-sale-network
    dev:
        container_name: cam_web_sale
        image: cam_web_sale:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile

        ports:
            - 3030:3030
        networks:
            - web-cam-sale-network
        depends_on: 
            - db
        restart: always
    
volumes:
    postgresql_cam_web_sale:
        driver: local


networks:
    web-cam-sale-network:
