version: '3.8'

services:
    db:
        image: bitnami/postgresql:11
        ports:  
            - 5438:5432  
        volumes:  
            - postgresql_data:/bitnami/postgresql  
        env_file: ./.docker.env
        restart: always  
        networks:  
            - cam-web-sale-network
    dev:
        container_name: cam_web_sale_dev
        image: cam-web-sale-dev:1.0.0
        env_file: ./.docker.env
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3020:3020
        networks:
            - cam-web-sale-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: cam_web_sale_prod
        image: cam-web-sale-prod:1.0.0
        env_file: ./.docker.env
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3030:3030
        networks:
            - cam-web-sale-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    cam-web-sale-network: