version: '3.8'

services:
    dev:
        container_name: cam_web_sale_dev
        image: cam-web-sale-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3020:3020
        networks:
            - cam-web-sale-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: cam_web_sale_prod
        image: cam-web-sale-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3030:3030
        networks:
            - cam-web-sale-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    cam-web-sale-network: